from tkinter import *
root=Tk()
root.title("Resturant Table reservation")
root.iconbitmap("abc.ico")
root.geometry("500x500")
root.resizable(0,0)
#Button(text="Log In",width=20).pack()
#greenbutton = Button(root, text ="RIGHT",fg= "black")
#greenbutton.pack(_side = RIGHT )
#bluebutton = Button(root, text_= "TOP", fg="blue")
#bluebutton.pack(side= TOP )
#blackbutton = Button(root, text = "BOTTOM", fg= "red")
#blackbutton.pack( side = BOTTOM)
#name = Label(root, text = "Name")
#name.grid(row=0, column=0)
#e1 = Entry(root)
#e1.grid(row=0, column=1)
#password = Label(root, text="Password")
#password.grid(row=1, column=0)
#e2 = Entry(root)
#e2.grid(row=1, column=1)
#submit = Button(root, text="Submit")
#submit.grid(row=4, column=1)
name = Label(root, text = "Name").place(x=30, y=50)
address = Label(root, text = "Address").place(x=30, y=90)
contact = Label(root, text = "Contact").place(x=30, y=130)
e1 = Entry(root).place(x=80, y=50)
e2 = Entry(root).place(x=80, y=90)
e3 = Entry(root).place(x=80, y=130)
Button(root, text="Log in", width=20).place(x=30, y=170)
def login():
    print("Login Successful")
login()

root.mainloop()



mainloop()